import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, SafeAreaView, ScrollView } from 'react-native';
import Header from '../../components/Header'; import Card from '../../components/Card'; import Badge from '../../components/Badge'; import LoadingSpinner from '../../components/LoadingSpinner'; import EmptyState from '../../components/EmptyState';
import { getSessionDetail } from '../../api/progress'; import { COLORS, FONTS, RADIUS, SPACING } from '../../constants/theme';

const HistoryDetailScreen = ({ route }) => {
  const { sessionId } = route.params; const [session, setSession] = useState(null); const [error, setError] = useState('');
  useEffect(() => { getSessionDetail(sessionId).then(setSession).catch(e => setError(e.response?.data?.message || 'Unable to load this session.')); }, [sessionId]);
  if (!session && !error) return <LoadingSpinner fullScreen message="Loading session..." />;
  if (error) return <SafeAreaView style={styles.safe}><Header title="Session Summary" showBack /><EmptyState title="Session unavailable" message={error} /></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><Header title="Session Summary" showBack /><ScrollView contentContainerStyle={styles.scroll}><Card style={styles.summary}><Text style={styles.topic}>{session.topic}</Text><Text style={styles.muted}>{new Date(session.createdAt).toLocaleString()}</Text><View style={styles.stats}><Text style={styles.stat}>{session.accuracy}%{`\n`}<Text style={styles.label}>Score</Text></Text><Text style={styles.stat}>{session.correctAnswers}/{session.totalQuestions}{`\n`}<Text style={styles.label}>Correct</Text></Text><Text style={styles.stat}>{session.duration || 0} min{`\n`}<Text style={styles.label}>Time</Text></Text></View></Card><Text style={styles.heading}>Exercises</Text>{session.exercises?.map((entry, index) => { const exercise = entry.exerciseData || {}; return <Card key={index} style={styles.exercise}><View style={styles.row}><Text style={styles.question}>Question {index + 1}</Text><Badge text={entry.isCorrect ? 'Correct' : 'Incorrect'} variant={entry.isCorrect ? 'success' : 'error'} /></View><Text style={styles.text}>{exercise.question || exercise.prompt}</Text><Text style={styles.muted}>Your answer: {String(entry.userAnswer || 'No answer')}</Text>{!entry.isCorrect && <Text style={styles.correct}>Correct answer: {String(entry.feedback?.correctAnswer || exercise.correctAnswer || '—')}</Text>}<Text style={styles.feedback}>{entry.feedback?.explanation || ''}</Text></Card>; })}</ScrollView></SafeAreaView>;
};
const styles = StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},scroll:{padding:SPACING.base,paddingBottom:SPACING.xxl},summary:{padding:SPACING.xl,alignItems:'center'},topic:{...FONTS.h3,color:COLORS.text},muted:{...FONTS.small,color:COLORS.textSecondary,marginTop:4},stats:{width:'100%',flexDirection:'row',justifyContent:'space-between',marginTop:SPACING.lg},stat:{...FONTS.h3,color:COLORS.primaryDark,textAlign:'center'},label:{...FONTS.small,color:COLORS.textSecondary},heading:{...FONTS.h4,color:COLORS.text,marginVertical:SPACING.base},exercise:{padding:SPACING.base},row:{flexDirection:'row',justifyContent:'space-between',marginBottom:SPACING.sm},question:{...FONTS.small,color:COLORS.textSecondary},text:{...FONTS.regular,color:COLORS.text,marginBottom:SPACING.sm},correct:{...FONTS.small,color:COLORS.success,marginTop:4},feedback:{...FONTS.small,color:COLORS.primaryDark,marginTop:SPACING.sm,backgroundColor:COLORS.primaryLighter,padding:SPACING.sm,borderRadius:RADIUS.md}});
export default HistoryDetailScreen;
